const CONFIG={SUPABASE_URL:'YOUR_SUPABASE_URL',SUPABASE_PUBLISHABLE_KEY:'YOUR_SUPABASE_PUBLISHABLE_KEY',ADMIN_EMAIL:'admin@sushian.com'};
const ready=CONFIG.SUPABASE_URL.startsWith('http')&&!CONFIG.SUPABASE_URL.includes('YOUR_')&&!CONFIG.SUPABASE_PUBLISHABLE_KEY.includes('YOUR_');
const loginView=document.getElementById('loginView'),adminView=document.getElementById('adminView'),loginForm=document.getElementById('loginForm'),beatForm=document.getElementById('beatForm'),loginMessage=document.getElementById('loginMessage'),uploadMessage=document.getElementById('uploadMessage');
let supabaseClient=null;
function message(el,text,error=false){el.textContent=text;el.style.color=error?'#ff7b7b':'#d8ff38'}
function showAdmin(user){loginView.classList.add('hidden');adminView.classList.remove('hidden');document.getElementById('adminEmail').textContent=user.email||'';document.getElementById('authStatus').textContent='Authenticated';loadLibrary()}
async function boot(){if(!ready){message(loginMessage,'Supabase is not configured yet. Add your project URL, publishable key and admin email in admin.js.',true);return}supabaseClient=window.supabase.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_PUBLISHABLE_KEY);document.getElementById('storageStatus').textContent='Connected';const {data:{session}}=await supabaseClient.auth.getSession();if(session?.user?.email===CONFIG.ADMIN_EMAIL)showAdmin(session.user);else if(session)await supabaseClient.auth.signOut();supabaseClient.auth.onAuthStateChange((_event,session)=>{if(session?.user?.email===CONFIG.ADMIN_EMAIL)showAdmin(session.user);else{loginView.classList.remove('hidden');adminView.classList.add('hidden')}})}
loginForm.addEventListener('submit',async e=>{e.preventDefault();if(!ready){message(loginMessage,'Configure Supabase first.',true);return}message(loginMessage,'Signing in…');const {data,error}=await supabaseClient.auth.signInWithPassword({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value});if(error){message(loginMessage,error.message,true);return}if(data.user?.email!==CONFIG.ADMIN_EMAIL){await supabaseClient.auth.signOut();message(loginMessage,'This account is not authorized for the creator panel.',true);return}showAdmin(data.user)});
document.getElementById('logout').onclick=async()=>{if(supabaseClient)await supabaseClient.auth.signOut()};
async function loadLibrary(){if(!supabaseClient)return;const {data,error}=await supabaseClient.from('beats').select('*').order('created_at',{ascending:false});if(error){document.getElementById('beatCount').textContent='—';return}document.getElementById('beatCount').textContent=data.length;document.getElementById('libraryGrid').innerHTML=data.map(b=>`<article class="library-item"><h3>${escapeHtml(b.title)}</h3><p>${escapeHtml(b.genre)} · ${b.bpm} BPM · ${escapeHtml(b.key)}<br>$${Number(b.price).toFixed(0)} · ${escapeHtml(b.type)}</p>${b.preview_url?`<audio controls preload="none" src="${escapeAttr(b.preview_url)}"></audio>`:''}</article>`).join('')||'<p class="muted">No beats published yet.</p>'}
beatForm.addEventListener('submit',async e=>{e.preventDefault();if(!supabaseClient){message(uploadMessage,'Configure Supabase first.',true);return}const file=document.getElementById('audio').files[0];if(!file){message(uploadMessage,'Choose an audio file.',true);return}if(!file.type.startsWith('audio/')){message(uploadMessage,'Only audio files are allowed.',true);return}message(uploadMessage,'Uploading audio…');const slug=document.getElementById('title').value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const path=`previews/${Date.now()}-${slug}.${file.name.split('.').pop().toLowerCase()}`;const {error:uploadError}=await supabaseClient.storage.from('beat-previews').upload(path,file,{contentType:file.type,upsert:false});if(uploadError){message(uploadMessage,uploadError.message,true);return}const {data:urlData}=supabaseClient.storage.from('beat-previews').getPublicUrl(path);const row={title:document.getElementById('title').value.trim(),genre:document.getElementById('genre').value,bpm:Number(document.getElementById('bpm').value),key:document.getElementById('key').value.trim(),price:Number(document.getElementById('price').value),type:document.getElementById('type').value,audio_path:path,preview_url:urlData.publicUrl};const {error:dbError}=await supabaseClient.from('beats').insert(row);if(dbError){await supabaseClient.storage.from('beat-previews').remove([path]);message(uploadMessage,dbError.message,true);return}message(uploadMessage,'Beat published successfully.');beatForm.reset();document.getElementById('bpm').value=140;document.getElementById('price').value=29;loadLibrary()});
const drop=document.getElementById('dropZone');['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{if(e.dataTransfer.files.length)document.getElementById('audio').files=e.dataTransfer.files});
function escapeHtml(s){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}function escapeAttr(s){return escapeHtml(s)}
boot();