const beats=[{title:'NOCTURNE',genre:'DARK TRAP',bpm:140,key:'F# MIN',price:29,type:'dark',audio:'assets/nocturne.mp3'},{title:'BLACKOUT',genre:'TRAP',bpm:150,key:'C MIN',price:39,type:'trap',audio:'assets/blackout.mp3'},{title:'AFTERIMAGE',genre:'CINEMATIC',bpm:128,key:'D MIN',price:49,type:'cinematic',audio:'assets/afterimage.mp3'},{title:'VOID',genre:'DARK TRAP',bpm:144,key:'A MIN',price:35,type:'dark',audio:'assets/void.mp3'},{title:'MIRROR',genre:'TRAP',bpm:138,key:'G MIN',price:29,type:'trap',audio:'assets/mirror.mp3'},{title:'LAST LIGHT',genre:'CINEMATIC',bpm:120,key:'E MIN',price:45,type:'cinematic',audio:'assets/last-light.mp3'}];
const licenses={Basic:{label:'Basic',multiplier:1},Premium:{label:'Premium',multiplier:2},Unlimited:{label:'Unlimited',multiplier:4}};
let cart=JSON.parse(localStorage.getItem('sushian-cart')||'[]').filter(x=>beats.some(b=>b.title===x.title)).map(x=>({...x,license:licenses[x.license]?x.license:'Basic'}));
let player=null,activeButton=null,currentIndex=-1;
const grid=document.getElementById('beatGrid'),cartEl=document.getElementById('cart'),scrim=document.getElementById('scrim'),sitePlayer=document.getElementById('sitePlayer');
document.getElementById('year').textContent=new Date().getFullYear();
function money(n){return '$'+Number(n).toFixed(2)}
function priceFor(b,license){return b.price*licenses[license].multiplier}
function save(){localStorage.setItem('sushian-cart',JSON.stringify(cart))}
function render(filter='all'){const list=beats.filter(b=>filter==='all'||b.type===filter);grid.innerHTML=list.map((b,i)=>`<article class="beat"><div class="cover"><span class="cover-tag">${String(beats.indexOf(b)+1).padStart(2,'0')} / ORIGINAL</span></div><div class="beat-info"><div class="beat-meta"><span>${b.genre}</span><span>${b.bpm} BPM · ${b.key}</span></div><h3>${b.title}</h3><div class="beat-bottom"><span class="price">from ${money(b.price)}</span><div><button class="play" data-play="${b.title}" aria-label="Preview ${b.title}">▶</button><button class="button ghost add" data-add="${b.title}">Add</button></div></div></div></article>`).join('');grid.querySelectorAll('[data-add]').forEach(x=>x.onclick=()=>add(x.dataset.add));grid.querySelectorAll('[data-play]').forEach(x=>x.onclick=()=>preview(x,x.dataset.play))}
function add(title){const b=beats.find(x=>x.title===title);if(!b)return;if(!cart.some(x=>x.title===title))cart.push({...b,license:'Basic'});save();renderCart();openCart()}
function renderCart(){document.getElementById('cartCount').textContent=cart.length;document.getElementById('cartItems').innerHTML=cart.length?cart.map((b,i)=>`<div class="cart-item"><div><strong>${b.title}</strong><br><select class="license-select" data-license-index="${i}" aria-label="License for ${b.title}">${Object.keys(licenses).map(k=>`<option value="${k}" ${b.license===k?'selected':''}>${licenses[k].label}</option>`).join('')}</select></div><div><span class="price">${money(priceFor(b,b.license))}</span><button class="remove" data-remove="${i}" aria-label="Remove ${b.title}">×</button></div></div>`).join(''):'<p class="empty">Your cart is empty.</p>';document.getElementById('cartTotal').textContent=money(cart.reduce((s,b)=>s+priceFor(b,b.license),0));document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{cart.splice(+x.dataset.remove,1);save();renderCart()});document.querySelectorAll('[data-license-index]').forEach(x=>x.onchange=()=>{cart[+x.dataset.licenseIndex].license=x.value;save();renderCart()})}
function openCart(){cartEl.classList.add('open');scrim.classList.add('show');cartEl.setAttribute('aria-hidden','false')}
function closeCart(){cartEl.classList.remove('open');scrim.classList.remove('show');cartEl.setAttribute('aria-hidden','true')}
document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;scrim.onclick=closeCart;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCart()});
document.getElementById('checkout').onclick=()=>{if(!cart.length){alert('Your cart is empty.');return}alert('Checkout UI is ready. The secure payment backend is the next integration step.')};
document.querySelectorAll('[data-license]').forEach(x=>x.onclick=()=>{const name=x.dataset.license.replace(' License','');if(cart[0]){cart[0].license=name;save();renderCart();openCart()}else{document.getElementById('beats').scrollIntoView({behavior:'smooth'});alert(`${name} selected. Add a beat to your cart.`)}});
document.querySelectorAll('#filters button').forEach(x=>x.onclick=()=>{document.querySelectorAll('#filters button').forEach(b=>b.classList.remove('active'));x.classList.add('active');render(x.dataset.filter)});
function setPlayerUI(b){document.getElementById('playerTitle').textContent=b.title;document.getElementById('playerSub').textContent=`${b.genre} · ${b.bpm} BPM · ${b.key}`;document.getElementById('playerToggle').textContent='Ⅱ';sitePlayer.classList.add('active')}
function preview(btn,title){const index=beats.findIndex(x=>x.title===title);if(index<0)return;if(currentIndex===index&&player){if(player.paused){player.play().catch(()=>{});btn.classList.add('playing');btn.textContent='Ⅱ';document.getElementById('playerToggle').textContent='Ⅱ'}else{stopPreview()}return}stopPreview();currentIndex=index;const b=beats[index];player=new Audio(b.audio);player.preload='metadata';player.volume=Number(document.getElementById('playerVolume').value);player.addEventListener('ended',()=>nextTrack());player.addEventListener('timeupdate',updateProgress);player.addEventListener('loadedmetadata',updateProgress);player.play().then(()=>{activeButton=btn;btn.classList.add('playing');btn.textContent='Ⅱ';setPlayerUI(b)}).catch(()=>{alert(`Preview file not found yet: ${b.audio}. Upload the MP3 to the assets folder or connect the admin storage.`);player=null;currentIndex=-1})}
function stopPreview(){if(player){player.pause();player.currentTime=0}if(activeButton){activeButton.classList.remove('playing');activeButton.textContent='▶'}if(document.getElementById('playerToggle'))document.getElementById('playerToggle').textContent='▶';player=null;activeButton=null;updateProgress()}
function loadTrack(index,autoplay=true){if(index<0||index>=beats.length)return;const b=beats[index];stopPreview();currentIndex=index;player=new Audio(b.audio);player.preload='metadata';player.volume=Number(document.getElementById('playerVolume').value);player.addEventListener('ended',nextTrack);player.addEventListener('timeupdate',updateProgress);player.addEventListener('loadedmetadata',updateProgress);setPlayerUI(b);if(autoplay)player.play().catch(()=>{alert(`Preview file not found yet: ${b.audio}.`);stopPreview()});}
function nextTrack(){loadTrack((currentIndex+1)%beats.length,true)}
function prevTrack(){loadTrack((currentIndex-1+beats.length)%beats.length,true)}
function updateProgress(){if(!player||!Number.isFinite(player.duration)||player.duration<=0){document.getElementById('playerProgressFill').style.width='0%';return}const pct=(player.currentTime/player.duration)*100;document.getElementById('playerProgressFill').style.width=`${pct}%`;document.getElementById('playerProgress').setAttribute('aria-valuenow',String(Math.round(pct)))}
document.getElementById('playerToggle').onclick=()=>{if(!player){loadTrack(0,true);return}if(player.paused){player.play().catch(()=>{});document.getElementById('playerToggle').textContent='Ⅱ'}else{player.pause();document.getElementById('playerToggle').textContent='▶'}};document.getElementById('playerNext').onclick=nextTrack;document.getElementById('playerPrev').onclick=prevTrack;document.getElementById('playerVolume').oninput=e=>{if(player)player.volume=Number(e.target.value)};document.getElementById('playerProgress').onclick=e=>{if(!player||!Number.isFinite(player.duration))return;const r=e.currentTarget.getBoundingClientRect();player.currentTime=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*player.duration};
render();renderCart();save();